package storage

// runtimeContractColumns is the writable catalog surface consumed by runtime
// SQL. Defaults are included only where writers omit the column and depend on
// PostgreSQL to supply the value.
func runtimeContractColumns() []ColumnDefinition {
	return []ColumnDefinition{
		{Table: "ai_briefing_blocks", Column: "date", DataType: "text", Nullable: false},
		{Table: "ai_briefing_blocks", Column: "lang", DataType: "text", Nullable: false},
		{Table: "ai_briefing_blocks", Column: "block", DataType: "text", Nullable: false},
		{Table: "ai_briefing_blocks", Column: "text", DataType: "text", Nullable: false},
		{Table: "ai_briefing_blocks", Column: "inputs_hash", DataType: "text", Nullable: false},
		{Table: "ai_briefing_blocks", Column: "created_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "ai_briefings", Column: "date", DataType: "text", Nullable: false},
		{Table: "ai_briefings", Column: "insight", DataType: "text", Nullable: false},
		{Table: "ai_briefings", Column: "created_at", DataType: "timestamp with time zone", Nullable: false, Default: "now()", RequireDefault: true},
		{Table: "ai_briefings", Column: "sent_at", DataType: "timestamp with time zone", Nullable: true},
		{Table: "ai_briefings", Column: "request_payload", DataType: "jsonb", Nullable: true},
		{Table: "ai_briefings", Column: "lang", DataType: "text", Nullable: false, Default: "''::text", RequireDefault: true},
		{Table: "auth_sessions", Column: "id_hash", DataType: "text", Nullable: false},
		{Table: "auth_sessions", Column: "created_at", DataType: "timestamp with time zone", Nullable: false, Default: "now()", RequireDefault: true},
		{Table: "auth_sessions", Column: "expires_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "auth_sessions", Column: "last_seen_at", DataType: "timestamp with time zone", Nullable: true},
		{Table: "chip_calibrations", Column: "sub_score", DataType: "text", Nullable: false},
		{Table: "chip_calibrations", Column: "target_kind", DataType: "text", Nullable: false},
		{Table: "chip_calibrations", Column: "source_epoch", DataType: "text", Nullable: false},
		{Table: "chip_calibrations", Column: "status", DataType: "text", Nullable: false},
		{Table: "chip_calibrations", Column: "method", DataType: "text", Nullable: false},
		{Table: "chip_calibrations", Column: "cutoff", DataType: "real", Nullable: true},
		{Table: "chip_calibrations", Column: "p80", DataType: "real", Nullable: true},
		{Table: "chip_calibrations", Column: "base_rate", DataType: "real", Nullable: true},
		{Table: "chip_calibrations", Column: "calibration_window_days", DataType: "integer", Nullable: false},
		{Table: "chip_calibrations", Column: "n_eligible", DataType: "integer", Nullable: false},
		{Table: "chip_calibrations", Column: "n_positives", DataType: "integer", Nullable: false},
		{Table: "chip_calibrations", Column: "computed_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "context_prompt_interactions", Column: "prompt_id", DataType: "text", Nullable: false},
		{Table: "context_prompt_interactions", Column: "signal_date", DataType: "date", Nullable: false},
		{Table: "context_prompt_interactions", Column: "prompt_local_date", DataType: "date", Nullable: false},
		{Table: "context_prompt_interactions", Column: "detected_reason", DataType: "text", Nullable: false},
		{Table: "context_prompt_interactions", Column: "detector_version", DataType: "text", Nullable: false},
		{Table: "context_prompt_interactions", Column: "status", DataType: "text", Nullable: false},
		{Table: "context_prompt_interactions", Column: "category", DataType: "text", Nullable: true},
		{Table: "context_prompt_interactions", Column: "source", DataType: "text", Nullable: true},
		{Table: "context_prompt_interactions", Column: "prompt_message_id", DataType: "bigint", Nullable: true},
		{Table: "context_prompt_interactions", Column: "prompted_at", DataType: "timestamp with time zone", Nullable: true},
		{Table: "context_prompt_interactions", Column: "expires_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "context_prompt_interactions", Column: "answered_at", DataType: "timestamp with time zone", Nullable: true},
		{Table: "context_prompt_interactions", Column: "allowed_categories", DataType: "jsonb", Nullable: false},
		{Table: "context_prompt_interactions", Column: "metadata", DataType: "jsonb", Nullable: false},
		{Table: "context_prompt_interactions", Column: "created_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "context_prompt_interactions", Column: "updated_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "derived_metric_feedback", Column: "metric_name", DataType: "text", Nullable: false},
		{Table: "derived_metric_feedback", Column: "metric_date", DataType: "date", Nullable: false},
		{Table: "derived_metric_feedback", Column: "channel", DataType: "text", Nullable: false},
		{Table: "derived_metric_feedback", Column: "proposed_value", DataType: "jsonb", Nullable: false},
		{Table: "derived_metric_feedback", Column: "response", DataType: "text", Nullable: true},
		{Table: "derived_metric_feedback", Column: "corrected_value", DataType: "jsonb", Nullable: true},
		{Table: "derived_metric_feedback", Column: "prompt_message_id", DataType: "bigint", Nullable: true},
		{Table: "derived_metric_feedback", Column: "prompted_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "derived_metric_feedback", Column: "answered_at", DataType: "timestamp with time zone", Nullable: true},
		{Table: "derived_metric_feedback", Column: "metadata", DataType: "jsonb", Nullable: false, Default: "'{}'::jsonb", RequireDefault: true},
		{Table: "derived_metrics", Column: "metric_name", DataType: "text", Nullable: false},
		{Table: "derived_metrics", Column: "metric_date", DataType: "date", Nullable: false},
		{Table: "derived_metrics", Column: "value_type", DataType: "text", Nullable: false},
		{Table: "derived_metrics", Column: "value_numeric", DataType: "double precision", Nullable: true},
		{Table: "derived_metrics", Column: "value_text", DataType: "text", Nullable: true},
		{Table: "derived_metrics", Column: "value_timestamp", DataType: "timestamp with time zone", Nullable: true},
		{Table: "derived_metrics", Column: "value_json", DataType: "jsonb", Nullable: true},
		{Table: "derived_metrics", Column: "unit", DataType: "text", Nullable: false, Default: "''::text", RequireDefault: true},
		{Table: "derived_metrics", Column: "state", DataType: "text", Nullable: false},
		{Table: "derived_metrics", Column: "formula_version", DataType: "text", Nullable: false},
		{Table: "derived_metrics", Column: "inputs_hash", DataType: "text", Nullable: false},
		{Table: "derived_metrics", Column: "calculated_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "derived_metrics", Column: "finalized_at", DataType: "timestamp with time zone", Nullable: true},
		{Table: "derived_metrics", Column: "metadata", DataType: "jsonb", Nullable: false, Default: "'{}'::jsonb", RequireDefault: true},
		{Table: "daily_scores", Column: "date", DataType: "text", Nullable: false},
		{Table: "daily_scores", Column: "readiness", DataType: "integer", Nullable: true},
		{Table: "daily_scores", Column: "score_version", DataType: "integer", Nullable: true},
		{Table: "daily_scores", Column: "computed_at", DataType: "text", Nullable: false},
		{Table: "daily_scores", Column: "hrv_avg", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "rhr_avg", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "sleep_total", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "sleep_deep", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "sleep_rem", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "sleep_core", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "sleep_awake", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "steps", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "calories", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "exercise_min", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "spo2_avg", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "vo2_avg", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "resp_avg", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "energy_capacity", DataType: "integer", Nullable: true},
		{Table: "daily_scores", Column: "energy_eod_current", DataType: "integer", Nullable: true},
		{Table: "daily_scores", Column: "energy_drain", DataType: "integer", Nullable: true},
		{Table: "daily_scores", Column: "energy_verdict", DataType: "text", Nullable: true},
		{Table: "daily_scores", Column: "baseline_hr_overnight", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "sustained_hr_load", DataType: "real", Nullable: true},
		{Table: "daily_scores", Column: "stress_flags", DataType: "ARRAY", UDTName: "_text", Nullable: true},
		{Table: "daily_scores", Column: "sleep_unspecified", DataType: "real", Nullable: true},
		{Table: "energy_snapshots", Column: "ts_bucket", DataType: "timestamp with time zone", Nullable: false},
		{Table: "energy_snapshots", Column: "date", DataType: "text", Nullable: false},
		{Table: "energy_snapshots", Column: "bank", DataType: "integer", Nullable: false},
		{Table: "energy_snapshots", Column: "drain_delta", DataType: "integer", Nullable: false},
		{Table: "energy_snapshots", Column: "restore_delta", DataType: "integer", Nullable: false},
		{Table: "energy_snapshots", Column: "formula_version", DataType: "integer", Nullable: false},
		{Table: "energy_snapshots", Column: "components", DataType: "jsonb", Nullable: true},
		{Table: "energy_snapshots", Column: "flags", DataType: "ARRAY", UDTName: "_text", Nullable: false},
		{Table: "energy_snapshots", Column: "computed_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "feature_snapshots", Column: "date", DataType: "text", Nullable: false},
		{Table: "feature_snapshots", Column: "sub_score", DataType: "text", Nullable: false},
		{Table: "feature_snapshots", Column: "features", DataType: "jsonb", Nullable: false},
		{Table: "feature_snapshots", Column: "source_epoch", DataType: "text", Nullable: false},
		{Table: "feature_snapshots", Column: "feature_version", DataType: "integer", Nullable: false},
		{Table: "feature_snapshots", Column: "computed_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "health_records", Column: "id", DataType: "bigint", Nullable: false, Default: "nextval('health_records_id_seq'::regclass)", RequireDefault: true},
		{Table: "health_records", Column: "received_at", DataType: "timestamp with time zone", Nullable: true, Default: "now()", RequireDefault: true},
		{Table: "health_records", Column: "automation_name", DataType: "text", Nullable: true},
		{Table: "health_records", Column: "automation_id", DataType: "text", Nullable: true},
		{Table: "health_records", Column: "automation_aggregation", DataType: "text", Nullable: true},
		{Table: "health_records", Column: "automation_period", DataType: "text", Nullable: true},
		{Table: "health_records", Column: "session_id", DataType: "text", Nullable: true},
		{Table: "health_records", Column: "content_type", DataType: "text", Nullable: true},
		{Table: "health_records", Column: "payload", DataType: "text", Nullable: true},
		{Table: "health_records", Column: "processing_status", DataType: "text", Nullable: false, Default: "'complete'::text", RequireDefault: true},
		{Table: "health_records", Column: "processing_kind", DataType: "text", Nullable: false, Default: "'all'::text", RequireDefault: true},
		{Table: "health_records", Column: "processing_error", DataType: "text", Nullable: true},
		{Table: "health_records", Column: "processed_at", DataType: "timestamp with time zone", Nullable: true},
		{Table: "hourly_metrics", Column: "metric_name", DataType: "text", Nullable: false},
		{Table: "hourly_metrics", Column: "hour", DataType: "text", Nullable: false},
		{Table: "hourly_metrics", Column: "source", DataType: "text", Nullable: false},
		{Table: "hourly_metrics", Column: "avg_val", DataType: "real", Nullable: false},
		{Table: "hourly_metrics", Column: "min_val", DataType: "real", Nullable: false},
		{Table: "hourly_metrics", Column: "max_val", DataType: "real", Nullable: false},
		{Table: "import_run_coverage", Column: "import_run_id", DataType: "bigint", Nullable: false},
		{Table: "import_run_coverage", Column: "metric_name", DataType: "text", Nullable: false},
		{Table: "import_run_coverage", Column: "source", DataType: "text", Nullable: false},
		{Table: "import_run_coverage", Column: "local_date", DataType: "text", Nullable: false},
		{Table: "import_runs", Column: "id", DataType: "bigint", Nullable: false, Default: "nextval('import_runs_id_seq'::regclass)", RequireDefault: true},
		{Table: "import_runs", Column: "origin", DataType: "text", Nullable: false},
		{Table: "import_runs", Column: "source_name", DataType: "text", Nullable: false},
		{Table: "import_runs", Column: "started_at", DataType: "timestamp with time zone", Nullable: false, Default: "now()", RequireDefault: true},
		{Table: "import_runs", Column: "finished_at", DataType: "timestamp with time zone", Nullable: true},
		{Table: "import_runs", Column: "snapshot_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "import_runs", Column: "status", DataType: "text", Nullable: false},
		{Table: "import_runs", Column: "min_date", DataType: "text", Nullable: true},
		{Table: "import_runs", Column: "max_date", DataType: "text", Nullable: true},
		{Table: "import_runs", Column: "parsed_points", DataType: "bigint", Nullable: false, Default: "0", RequireDefault: true},
		{Table: "import_runs", Column: "inserted_points", DataType: "bigint", Nullable: false, Default: "0", RequireDefault: true},
		{Table: "import_runs", Column: "updated_points", DataType: "bigint", Nullable: false, Default: "0", RequireDefault: true},
		{Table: "import_runs", Column: "deleted_points", DataType: "bigint", Nullable: false, Default: "0", RequireDefault: true},
		{Table: "import_runs", Column: "skipped_points", DataType: "bigint", Nullable: false, Default: "0", RequireDefault: true},
		{Table: "import_runs", Column: "parsed_workouts", DataType: "bigint", Nullable: false, Default: "0", RequireDefault: true},
		{Table: "import_runs", Column: "upserted_workouts", DataType: "bigint", Nullable: false, Default: "0", RequireDefault: true},
		{Table: "import_runs", Column: "deleted_workouts", DataType: "bigint", Nullable: false, Default: "0", RequireDefault: true},
		{Table: "import_runs", Column: "error", DataType: "text", Nullable: true},
		{Table: "import_runs", Column: "heartbeat_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "import_runs", Column: "lease_token", DataType: "uuid", Nullable: true},
		{Table: "import_stage_points", Column: "import_run_id", DataType: "bigint", Nullable: false},
		{Table: "import_stage_points", Column: "staged_seq", DataType: "bigint", Nullable: false, Default: "nextval('import_stage_points_staged_seq_seq'::regclass)", RequireDefault: true},
		{Table: "import_stage_points", Column: "metric_name", DataType: "text", Nullable: false},
		{Table: "import_stage_points", Column: "units", DataType: "text", Nullable: true},
		{Table: "import_stage_points", Column: "date", DataType: "text", Nullable: false},
		{Table: "import_stage_points", Column: "qty", DataType: "real", Nullable: true},
		{Table: "import_stage_points", Column: "source", DataType: "text", Nullable: false},
		{Table: "import_stage_points", Column: "local_date", DataType: "text", Nullable: false},
		{Table: "import_stage_workouts", Column: "import_run_id", DataType: "bigint", Nullable: false},
		{Table: "import_stage_workouts", Column: "staged_seq", DataType: "bigint", Nullable: false, Default: "nextval('import_stage_workouts_staged_seq_seq'::regclass)", RequireDefault: true},
		{Table: "import_stage_workouts", Column: "external_id", DataType: "text", Nullable: false},
		{Table: "import_stage_workouts", Column: "name", DataType: "text", Nullable: false},
		{Table: "import_stage_workouts", Column: "start_time", DataType: "timestamp with time zone", Nullable: false},
		{Table: "import_stage_workouts", Column: "end_time", DataType: "timestamp with time zone", Nullable: false},
		{Table: "import_stage_workouts", Column: "duration_sec", DataType: "double precision", Nullable: false},
		{Table: "import_stage_workouts", Column: "is_indoor", DataType: "boolean", Nullable: false},
		{Table: "import_stage_workouts", Column: "location", DataType: "text", Nullable: true},
		{Table: "import_stage_workouts", Column: "avg_hr_bpm", DataType: "double precision", Nullable: true},
		{Table: "import_stage_workouts", Column: "max_hr_bpm", DataType: "double precision", Nullable: true},
		{Table: "import_stage_workouts", Column: "energy_kcal", DataType: "double precision", Nullable: true},
		{Table: "import_stage_workouts", Column: "intensity", DataType: "double precision", Nullable: true},
		{Table: "import_stage_workouts", Column: "distance_km", DataType: "double precision", Nullable: true},
		{Table: "import_stage_workouts", Column: "avg_speed_kmh", DataType: "double precision", Nullable: true},
		{Table: "import_stage_workouts", Column: "max_speed_kmh", DataType: "double precision", Nullable: true},
		{Table: "import_stage_workouts", Column: "elevation_up_m", DataType: "double precision", Nullable: true},
		{Table: "import_stage_workouts", Column: "step_count_total", DataType: "integer", Nullable: true},
		{Table: "import_stage_workouts", Column: "step_cadence_spm", DataType: "double precision", Nullable: true},
		{Table: "import_stage_workouts", Column: "temperature_c", DataType: "double precision", Nullable: true},
		{Table: "import_stage_workouts", Column: "humidity_pct", DataType: "double precision", Nullable: true},
		{Table: "import_stage_workouts", Column: "hr_z1_sec", DataType: "integer", Nullable: true},
		{Table: "import_stage_workouts", Column: "hr_z2_sec", DataType: "integer", Nullable: true},
		{Table: "import_stage_workouts", Column: "hr_z3_sec", DataType: "integer", Nullable: true},
		{Table: "import_stage_workouts", Column: "hr_z4_sec", DataType: "integer", Nullable: true},
		{Table: "import_stage_workouts", Column: "hr_z5_sec", DataType: "integer", Nullable: true},
		{Table: "metric_points", Column: "id", DataType: "bigint", Nullable: false, Default: "nextval('metric_points_id_seq'::regclass)", RequireDefault: true},
		{Table: "metric_points", Column: "health_record_id", DataType: "bigint", Nullable: false},
		{Table: "metric_points", Column: "received_at", DataType: "timestamp with time zone", Nullable: true, Default: "now()", RequireDefault: true},
		{Table: "metric_points", Column: "metric_name", DataType: "text", Nullable: false},
		{Table: "metric_points", Column: "units", DataType: "text", Nullable: true},
		{Table: "metric_points", Column: "date", DataType: "text", Nullable: false},
		{Table: "metric_points", Column: "qty", DataType: "real", Nullable: true},
		{Table: "metric_points", Column: "source", DataType: "text", Nullable: true},
		{Table: "metric_points", Column: "quality", DataType: "text", Nullable: false, Default: "'ok'::text", RequireDefault: true},
		{Table: "metric_points", Column: "origin", DataType: "text", Nullable: false, Default: "'live'::text", RequireDefault: true},
		{Table: "metric_points", Column: "import_run_id", DataType: "bigint", Nullable: true},
		{Table: "metric_points", Column: "source_snapshot_at", DataType: "timestamp with time zone", Nullable: true},
		{Table: "minute_metrics", Column: "metric_name", DataType: "text", Nullable: false},
		{Table: "minute_metrics", Column: "minute", DataType: "text", Nullable: false},
		{Table: "minute_metrics", Column: "source", DataType: "text", Nullable: false},
		{Table: "minute_metrics", Column: "avg_val", DataType: "real", Nullable: false},
		{Table: "minute_metrics", Column: "min_val", DataType: "real", Nullable: false},
		{Table: "minute_metrics", Column: "max_val", DataType: "real", Nullable: false},
		{Table: "naive_baselines", Column: "date", DataType: "text", Nullable: false},
		{Table: "naive_baselines", Column: "sub_score", DataType: "text", Nullable: false},
		{Table: "naive_baselines", Column: "target_kind", DataType: "text", Nullable: false},
		{Table: "naive_baselines", Column: "baseline_kind", DataType: "text", Nullable: false},
		{Table: "naive_baselines", Column: "predicted_value", DataType: "real", Nullable: true},
		{Table: "naive_baselines", Column: "source_epoch", DataType: "text", Nullable: false},
		{Table: "naive_baselines", Column: "formula_version", DataType: "integer", Nullable: false},
		{Table: "naive_baselines", Column: "computed_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "naive_baselines", Column: "reason", DataType: "text", Nullable: true},
		{Table: "notification_deliveries", Column: "delivery_key", DataType: "text", Nullable: false},
		{Table: "notification_deliveries", Column: "status", DataType: "text", Nullable: false},
		{Table: "notification_deliveries", Column: "lease_token", DataType: "uuid", Nullable: false},
		{Table: "notification_deliveries", Column: "reserved_at", DataType: "timestamp with time zone", Nullable: false, Default: "now()", RequireDefault: true},
		{Table: "notification_deliveries", Column: "completed_at", DataType: "timestamp with time zone", Nullable: true},
		{Table: "notification_deliveries", Column: "error_code", DataType: "text", Nullable: true},
		{Table: "settings", Column: "key", DataType: "text", Nullable: false},
		{Table: "settings", Column: "value", DataType: "text", Nullable: false},
		{Table: "settings", Column: "updated_at", DataType: "text", Nullable: false},
		{Table: "source_epochs", Column: "epoch_id", DataType: "text", Nullable: false},
		{Table: "source_epochs", Column: "start_date", DataType: "text", Nullable: false},
		{Table: "source_epochs", Column: "end_date", DataType: "text", Nullable: true},
		{Table: "source_epochs", Column: "kind", DataType: "text", Nullable: false},
		{Table: "source_epochs", Column: "description", DataType: "text", Nullable: false},
		{Table: "source_epochs", Column: "detected_by", DataType: "text", Nullable: false},
		{Table: "source_epochs", Column: "confirmed", DataType: "boolean", Nullable: false},
		{Table: "source_epochs", Column: "created_at", DataType: "timestamp with time zone", Nullable: false, Default: "now()", RequireDefault: true},
		{Table: "source_epochs", Column: "updated_at", DataType: "timestamp with time zone", Nullable: false, Default: "now()", RequireDefault: true},
		{Table: "subjective_checkins", Column: "date", DataType: "text", Nullable: false},
		{Table: "subjective_checkins", Column: "source", DataType: "text", Nullable: false},
		{Table: "subjective_checkins", Column: "status", DataType: "text", Nullable: false},
		{Table: "subjective_checkins", Column: "answer", DataType: "text", Nullable: true},
		{Table: "subjective_checkins", Column: "prompt_message_id", DataType: "bigint", Nullable: true},
		{Table: "subjective_checkins", Column: "prompted_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "subjective_checkins", Column: "answered_at", DataType: "timestamp with time zone", Nullable: true},
		{Table: "subjective_checkins", Column: "expires_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "subjective_checkins", Column: "metadata", DataType: "jsonb", Nullable: false, Default: "'{}'::jsonb", RequireDefault: true},
		{Table: "target_snapshots", Column: "date", DataType: "text", Nullable: false},
		{Table: "target_snapshots", Column: "sub_score", DataType: "text", Nullable: false},
		{Table: "target_snapshots", Column: "target_kind", DataType: "text", Nullable: false},
		{Table: "target_snapshots", Column: "target_value", DataType: "real", Nullable: true},
		{Table: "target_snapshots", Column: "eligible", DataType: "boolean", Nullable: false},
		{Table: "target_snapshots", Column: "eligibility_reason", DataType: "text", Nullable: false},
		{Table: "target_snapshots", Column: "data_coverage", DataType: "jsonb", Nullable: true},
		{Table: "target_snapshots", Column: "source_epoch", DataType: "text", Nullable: false},
		{Table: "target_snapshots", Column: "formula_version", DataType: "integer", Nullable: false},
		{Table: "target_snapshots", Column: "computed_at", DataType: "timestamp with time zone", Nullable: false},
		{Table: "workouts", Column: "id", DataType: "bigint", Nullable: false, Default: "nextval('workouts_id_seq'::regclass)", RequireDefault: true},
		{Table: "workouts", Column: "received_at", DataType: "timestamp with time zone", Nullable: false, Default: "now()", RequireDefault: true},
		{Table: "workouts", Column: "health_record_id", DataType: "bigint", Nullable: true},
		{Table: "workouts", Column: "external_id", DataType: "text", Nullable: false},
		{Table: "workouts", Column: "name", DataType: "text", Nullable: false},
		{Table: "workouts", Column: "start_time", DataType: "timestamp with time zone", Nullable: false},
		{Table: "workouts", Column: "end_time", DataType: "timestamp with time zone", Nullable: false},
		{Table: "workouts", Column: "duration_sec", DataType: "double precision", Nullable: false},
		{Table: "workouts", Column: "is_indoor", DataType: "boolean", Nullable: false},
		{Table: "workouts", Column: "location", DataType: "text", Nullable: true},
		{Table: "workouts", Column: "avg_hr_bpm", DataType: "double precision", Nullable: true},
		{Table: "workouts", Column: "max_hr_bpm", DataType: "double precision", Nullable: true},
		{Table: "workouts", Column: "energy_kcal", DataType: "double precision", Nullable: true},
		{Table: "workouts", Column: "intensity", DataType: "double precision", Nullable: true},
		{Table: "workouts", Column: "distance_km", DataType: "double precision", Nullable: true},
		{Table: "workouts", Column: "avg_speed_kmh", DataType: "double precision", Nullable: true},
		{Table: "workouts", Column: "max_speed_kmh", DataType: "double precision", Nullable: true},
		{Table: "workouts", Column: "elevation_up_m", DataType: "double precision", Nullable: true},
		{Table: "workouts", Column: "step_count_total", DataType: "integer", Nullable: true},
		{Table: "workouts", Column: "step_cadence_spm", DataType: "double precision", Nullable: true},
		{Table: "workouts", Column: "temperature_c", DataType: "double precision", Nullable: true},
		{Table: "workouts", Column: "humidity_pct", DataType: "double precision", Nullable: true},
		{Table: "workouts", Column: "hr_z1_sec", DataType: "integer", Nullable: true},
		{Table: "workouts", Column: "hr_z2_sec", DataType: "integer", Nullable: true},
		{Table: "workouts", Column: "hr_z3_sec", DataType: "integer", Nullable: true},
		{Table: "workouts", Column: "hr_z4_sec", DataType: "integer", Nullable: true},
		{Table: "workouts", Column: "hr_z5_sec", DataType: "integer", Nullable: true},
		{Table: "workouts", Column: "origin", DataType: "text", Nullable: false},
		{Table: "workouts", Column: "import_run_id", DataType: "bigint", Nullable: true},
		{Table: "workouts", Column: "source_snapshot_at", DataType: "timestamp with time zone", Nullable: true},
	}
}
