package ai

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"health-receiver/internal/health"
)

// BlockSynthesis is the only block generated by AI insight v2. Historical
// SLEEP/YESTERDAY/RECOVERY/RECOMMENDATION rows remain readable as rollback
// data, but the active pipeline never generates them.
const BlockSynthesis = "SYNTHESIS"

// ─── input hashing ────────────────────────────────────────────────────────

// hashInputs marshals the per-block subset of metrics into stable JSON and
// returns a sha256 hex digest. Stable across runs because Go's encoding/json
// emits map keys in sorted order, and we package the subset as a struct.
func hashInputs(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return ""
	}
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

// HashSynthesis hashes the exact provider-facing evidence packet. The
// generation fingerprint is layered on by the storage orchestrator.
func HashSynthesis(evidence health.MorningInsightEvidence) string {
	return hashInputs(evidence)
}

type synthesisEnvelope struct {
	Explanation string `json:"explanation"`
}

var synthesisResponseSchema = &ResponseSchema{
	Name: "morning_insight_synthesis",
	Schema: map[string]any{
		"type": "object",
		"properties": map[string]any{
			"explanation": map[string]any{
				"type":        "string",
				"description": "One or two concise sentences explaining the server-selected verdict using only supplied evidence.",
			},
		},
		"required":             []string{"explanation"},
		"additionalProperties": false,
	},
}

var htmlTagPattern = regexp.MustCompile(`</?[a-zA-Z][^>]*>`)

// GenerateSynthesis makes the single provider call used by AI insight v2.
// The returned Text is the validated explanation rather than the raw JSON
// envelope, while request metadata remains available for observability.
func GenerateSynthesis(ctx context.Context, provider Provider, cfg ProviderConfig, evidenceJSON []byte, lang string) (GenerationResult, error) {
	if cfg.MaxOutputTokens <= 0 || cfg.MaxOutputTokens > SynthesisMaxTokens {
		cfg.MaxOutputTokens = SynthesisMaxTokens
	}
	generated, err := provider.Generate(ctx, cfg, GenerationRequest{
		Prompt:         systemPrompt,
		UserPayload:    evidenceJSON,
		Language:       lang,
		ResponseSchema: synthesisResponseSchema,
	})
	if err != nil {
		return generated, err
	}
	var envelope synthesisEnvelope
	if err := json.Unmarshal([]byte(generated.Text), &envelope); err != nil {
		return generated, fmt.Errorf("decode synthesis: %w", err)
	}
	explanation, err := validateSynthesisExplanation(envelope.Explanation)
	if err != nil {
		return generated, err
	}
	generated.Text = explanation
	return generated, nil
}

func validateSynthesisExplanation(value string) (string, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return "", fmt.Errorf("synthesis explanation is empty")
	}
	if words := len(strings.Fields(value)); words > 60 {
		return "", fmt.Errorf("synthesis explanation is too long: %d words", words)
	}
	if htmlTagPattern.MatchString(value) {
		return "", fmt.Errorf("synthesis explanation contains forbidden content")
	}
	lower := strings.ToLower(value)
	for _, forbidden := range []string{
		"```", "**",
		"diagnos", "диагноз", "klinički znač", "клинически знач",
	} {
		if strings.Contains(lower, forbidden) {
			return "", fmt.Errorf("synthesis explanation contains forbidden content")
		}
	}
	return value, nil
}
